from typing import Any, Union

class LongestMax:
    start_index: int
    end_index: int
    sequence: Any
    def __init__(self, sequence: list[Union[int, float]]) -> None: ...
    def maximum_sum(self): ...
    def subsequence(self): ...
