from typing import Union

class Array:
    def __init__(self, array: list[Union[int, float]]) -> None: ...
    def findPeak(self) -> tuple[Union[int, float], int]: ...
    def findAllPeaks(self) -> list[tuple[Union[int, float]], int]: ...
    def findFirstPeak(self) -> tuple[int, int]: ...
    def findMaxPeak(self) -> tuple[int, int]: ...
    def findMinPeak(self) -> tuple[int, int]: ...
